global:
  # DO NOT use this value in production, it's only for demo purposes
  # I usually use around 15s or 30s value
  scrape_interval: 1s
scrape_configs:
  - job_name: 'prom-demo'
    static_configs:
      - targets:
          - prom-demo:8081
  - job_name: 'postgres'
    static_configs:
      - targets:
          - postgres-exporter:9187
